spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/sannha?createDatabaseIfNotExist=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: root
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate